### ISSUE TITLE
Markdown parser not convert formatting characters without whitespace characters around them

### ISSUE THREAD

**Issue by luixxiul** [cryptpad/documentation#16]
It seems that the markdown parser for the user guide does not apply formatting characters properly. My guess is that they need whitespace characters around them.

For example, on https://docs.cryptpad.org/ja/user_guide/user_account.html#user-account, you should see `そのため**サービスの管理者に、あなたのパスワードを閲覧、取得、リセットすることはできません**。` in the first paragraph, as the formatting characters `**` are escaped. Since this kind of issue does not happen somewhere else, I assume this is a bug of the markdown parser.

![screenshot](https://github.com/cryptpad/documentation/assets/3362943/1eca0779-3a40-433f-a192-ffb179420152)

Since Japanese (like Chinese and Korean) language does not have the concept of whitespace character inside a sentence, it should appear just as "そのため**サービスの管理者に、あなたのパスワードを閲覧、取得、リセットすることはできません**。" without whitespace between `**` and characters.

**Comment by davidbenque** [comment]
Hello, the bug with the Markdown parser is that it's actually a reStructuredText parser :) and RST is a lot more stringent when it comes to whitespace and syntax quirks. I think you can achieve what you want by [escaping at the character level](https://stackoverflow.com/a/12781208).

Eventually I'd like to move the documentation to full Markdown or [Myst](https://mystmd.org/) but I can't say when we will have time to dedicate to this.

**Comment by luixxiul** [comment]
I see. Adding escape in each case requires a lot of tasks, and Markdown is definitely preferred to RST when it comes to compatibility with Asian languages.
