### ISSUE TITLE
Weird issues with lists

### ISSUE THREAD

**Issue by mthld** [cryptpad/documentation#21]
We have weird issues with bullet and numbered lists, probably some CSS:

<img width="1583" alt="Screenshot 2023-09-05 at 12 05 28" src="https://github.com/cryptpad/documentation/assets/41020854/a50a2703-b0c6-4c9d-b6ca-7aaf62ae2258">

<img width="609" alt="Screenshot 2023-09-05 at 12 05 37 1" src="https://github.com/cryptpad/documentation/assets/41020854/43169f10-f614-406c-b35b-9a2e5efa46f2">

<img width="609" alt="Screenshot 2023-09-05 at 12 05 37" src="https://github.com/cryptpad/documentation/assets/41020854/b3d0d751-9da8-4d7b-b94a-e7dc0940ac1e">

**Comment by JanRei** [comment]
I think this can be fixed by adopting [these changes](https://invent.kde.org/documentation/docs-krita-org/-/commit/c2e98c6933c0f0c17366ac21f81fb956fd2da685) to Krita's documentation theme. It should also improve the styling of captions and spacing below images.

**Comment by davidbenque** [comment]
![image](https://github.com/cryptpad/documentation/assets/11028490/9d715cd6-78cc-4364-a073-89f7eba47d73)

Thanks for the tip @JanRei it seems to have helped!

**Comment by davidbenque** [comment]
![image](https://github.com/cryptpad/documentation/assets/11028490/ab6dd0a0-f7f9-44d9-bc80-5d568278b137)

This list looks OK to me in Firefox, which browser are you using in your screenshot?
